[profile.default]
optimizer = true
optimizer_runs = 200
remappings = [
    "@semaphore-protocol/contracts/=lib/semaphore/packages/contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
scroll_sepolia = "https://sepolia.scroll.io"

[lint]
lint_on_build = false

[fmt]
